### PR TITLE
fix: re-export SWROptions

### PR DESCRIPTION
**Pull request by kouts**
This PR:
Re-exported `SWROptions` so that they can be used in query helper functions without having to import them separately from `swrev`

### CODE REVIEW

**Comment by kouts** [comment]
Thank you for this great library @ConsoleTVs.
I'm usually creating `query` functions as a pattern so it would be useful to have `SWROptions` re-exported.

**Comment by ConsoleTVs** [comment]
Absolutely, what do you think about exporting everything from swrev instead?

**Comment by kouts** [comment]
Makes sense to re-export everything from `swrev`.
We can either do it explicitly or implicitly i.e
```
export {
  SWR,
  SWRKey,
  SWRMutateValue,
  SWROptions,
  SWRMutateOptions,
  SWRRevalidateOptions,
  CacheClearOptions,
} from 'swrev'
```
or 

`export * from 'swrev'`
WDYT @ConsoleTVs, which one is more appropriate?

**Comment by ConsoleTVs** [comment]
`export * from 'swrev'` looks better imo

Modify this PR with this change and we good to merge!

**Comment by kouts** [comment]
Thanks @ConsoleTVs, fixed with [c68afa9](https://github.com/ConsoleTVs/vswr/pull/10/commits/c68afa91c89178d6a14d69bb25d07ac9d972f9ee)

**Comment by kouts** [comment]
I guess this can be merged now @ConsoleTVs.

**Pull request merged**
